
services:
  frontend-ui:
    build:
      context: ./battery-ui
    environment:
      NODE_ENV: production
    ports:
      - 3001:3000
    depends_on:
      - data-emulator

  streaming-service:
    build:
      context: ./streaming-service
    environment:
      NODE_ENV: production
      STREAMING_SERVICE_PORT: 3000

    ports:
      - 8080:3000
      
  data-emulator:
    build:
      context: ./data-emulator
    environment:
      NODE_ENV: production
      STREAMING_SERVICE_PORT: 3000
      STREAMING_SERVICE_HOST: streaming-service
    ports:
      - 3003:3000
    depends_on:
      - streaming-service
