name: CI & CD pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Install dependencies in react repo
      run: |
        cd battery-ui
        npm install
    
    - name: linting all projects
      run: |
        npm install
        npm run lint
  unit_test:
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: unit testing
      run: |
        npm install
        npm test

